# Generated by Django 5.2.2 on 2025-06-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_opt'),
    ]

    operations = [
        migrations.AddField(
            model_name='opt',
            name='tocken',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
