# Generated by Django 5.2.2 on 2025-06-08 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_opt_tocken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opt',
            new_name='Otp',
        ),
    ]
