# Generated by Django 5.2.2 on 2025-06-09 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_opt_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='tocken',
            new_name='token',
        ),
    ]
