# Generated by Django 5.2.2 on 2025-06-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orderitem_price_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('discount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
